### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by wojas007** [bkader/Skada-Revisited#10]
Hello,
first of all I must say I really like what You did with Skada and how you rewrote it. It is now very smooth and there are many useful things inside.

I don't know whether you want people to give you suggestions what could be changed within the addon, but I if you don't mind I have some ideas.

1) Damage taken details:
It is very nice, that you added possibility to check what spell/attack did how much damage on certain person (damage taken -> player -> list of spell/attacks). However maybe you could tweak "melee" source, since at the moment every melee attack made against player X is added together. During some encounters players (especially tanks) take melee damage not only from bosses but also from some adds (for example The Lich King encounter: ghouls, shambling horrors, etc). I have no idea how hard would this be, but maybe "melee" position could be listed like this:
1. Melee (source1) 1.34M
2. Melee (source2) 500K
3. Spell1 200K
4. Melee (source3) 150K

Also when I move mouse over the melee source I get info for max, avg, min hits (which is actually very important option: https://i.ibb.co/ZTwBB2q/image.png), but those values are added and averaged from every source. This is why maybe what I proposed would be more clear in a way.

If what I wrote above is too hard to implement, then maybe it could be put in different location:
Damage taken by spell -> Choose Melee -> and here chosing a player would move to next location with list of sources. Hovering mouse over certain source would show tooltip box with max, avg, min, damage and etc.
or
Enemy damage done -> Choose Boss -> and here chosing a player would move to next location with list spells/attacks. Hovering mouse over certain source would show tooltip with max, avg, min, damage and etc.

Adding all of these is probably pointless, but adding 1 of the 3 above could help a lot to see how much boss hits on average.

2) Fails:
There are two fails (already added by you), that could have more detailed description in the list.

a) Lady Deathwhisper Vengeful Shade/Vengeful Blast:
Today I tested it on normal difficulty, but I'm more interested in how it works on heroic version. On Hc they deal AoE damage when they catch their target and this can wipe the raid if all 3 shades hit melee target. So today from normal I see something like this: https://i.ibb.co/HG1Yvnj/image.png
and logs from same raid show something like this: https://i.ibb.co/spS1dQk/image.png
For some reason player Macieq i missing in fail list (I scrolled whole list) and also Deatrue got hit 3 times by vengeful shade instead of 1.
So what I'm interested in (unless it is too complicated) is to somehow show how many times player X triggered explosion of Vengeful Shade. If there was a list with time of each explosion then it would be perfect, but I assume this would be really hard to add.
Or maybe it would be easier to add this thing to Friendly Fire tab? I mean like when player X triggers explosion then damage done to all players from Vengeful Blast is added here. But maybe it is too hard too - I don't know.

b) Sindragosa Instability/Backlash:
So this I also haven't tested on heroic yet, but situation is somehow similar as above. Backlash on heroic deals AoE damage and could be either treated as friendly fire (if possible) or could be more detailed in Fails tab - each backlash explosion is treated separately and for each explosion there is info how many stacks exploded dealing how much damage (on hover over backlash). But maybe this is too hard too. For now I could only find these 2 (https://i.ibb.co/JpnPY7W/image.png)

BUT once again - I really like the revised addon already and I'm probably going to use it instead of the old Skada. Please, don't treat my suggestions as complaints. These are only my thoughts.

Regards,
Wojas

**Comment by MaelKoT** [comment]
As for the player Macieq, I think he received damage, because SOMEONE ELSE brought the spirit to him, and blew up about himself. Macieq just received damage, but is not guilty of anything. (and Vengeful Shadow only explodes about the player who summoned it, if I'm not confusing anything)

**Comment by wojas007** [comment]
It could have been the case, BUT as I mentioned above I show screenshots from Lady Deathwhisper normal encounter. On normal vengeful shades don't deal AoE damage on impact. So they can deal damage only to person who they're chasing.

**Comment by bkader** [comment]
![enemydamagedone](https://user-images.githubusercontent.com/4732702/99878407-6cfe5d00-2c05-11eb-90d9-d4856a6a9cb9.png)
Hi ! Sorry for my late reply and thanks a lot for your suggestions and I am glad you like what was done so far on the addon.
I received lately the same request and I was working on it (_whenever I have time_). The **Enemy damage done** is being rewritten to show almost exactly what you are both requesting. Just give me time and It shall be ready after testing it.

As for the Fails module, I will take a deeper look into it and try to enhance it even more.
Kind regards.

**Comment by wojas007** [comment]
Hey!
Thank you for your answer. SS you've sent looks like what I wanted. Can't wait for updates! Ofc there's no rush for anything.

Regards,
Wojas

**Comment by bkader** [comment]
![enemydamagedone](https://user-images.githubusercontent.com/4732702/99881029-785a8400-2c17-11eb-8520-e1ad6bbabb00.png)
This is kind of how I see it, I will update it after testing.

**Comment by wojas007** [comment]
Hey!
@bkader I downloaded latest version and I can see that you already put some updates on damage **damage done by spell** and **enemy damage done**. It looks like this for me:
1) https://i.ibb.co/N2Jc2f0/Wo-WScrn-Shot-112320-201729.jpg
2) https://i.ibb.co/tmxYRYw/Wo-WScrn-Shot-112320-205654.jpg
3) https://i.ibb.co/XYk2kzJ/Wo-WScrn-Shot-112320-205615.jpg
4) https://i.ibb.co/C0qy2m4/Wo-WScrn-Shot-112320-201731.jpg
IT IS EXACTLY WHAT I NEEDED!!

I uploaded these specific screenshots, because for some of our Halion tries Living Inferno and Living Ember auto atacks were listed as physical. BUT only for some of the tries. For most of the tries they were listed as Fire damage (and they should be fire). No sure whether it is server problem or addon problem.

Thanks again man!
Cheers!

**Comment by bkader** [comment]
Hi @wojas007 , glad you liked the changes that were done so far. I still have few things to test out before calling it **finished skada** but thanks to players like you, I am getting feedbacks, giving them temporarly solutions to test before validating them.

As for the **Auto Attack**, all melee attacks or auto attacks belong to the **Physical** schoo. You can clearly see on your screenshots that fire or shadow abilities are shown correctly. The spell school is returned by combat log events and the addon does nothing by receiving the info, recording it then displaying to the end user.

**Comment by wojas007** [comment]
Um what I meant was that Living Inferno and Living Embers deal fire damage with auto atacks.
And today when we were trying to kill halion for half of our tries addon recorded adds auto atacks as fire damage and for the rest it recorded it as physical damage. But I guess it is a combat log bug then. Thanks for the answer anyways

**Comment by wojas007** [comment]
Hey!
So the melee attacks are shown as I asked in the first post.
Only fail module could be more detailed, but if you won't be working on it further then you can close this ticket.

Cheers!
Wojas

**Comment by bkader** [comment]
Glad to see the absorbs and healing lua error is gone and game freezes as well. Thanks a lot for the feedback.
What kind of details you want for the fails module? Like time ... etc? If it's the case, I don't think it's necessary because fails are saved per segment, showing players who failed, what they failed and how many times and storing the exact time of the fail, in my opinion, isn't that important, unless it's a raid wiping fail.

**Comment by wojas007** [comment]
Well I'm mostly interested in 2 fails I wrote about in the first post. But I cannot be more specific at the moment, because I need few raids to get some screenshots + logs. Then I'll give you more detailed description. Please, give me few days, because lately I don't have as much time to play the game - sorry.

**Comment by wojas007** [comment]
Hey!
@bkader I had a chance to test fails today and I'm going to let go what I wanted from addon. I think it would be too complicated and it's not worth it.

HOWEVER, you could review Sindragosa fails, because today I didn't get a proper list of fails. No backlash at all and every other fail was not count properly. Unless my combat log bugged somehow.
Here's what I had after the fight and many people exploeded many times with backlash (I did on my druid Pniaq with 22 stacks)
https://i.ibb.co/nBQRLTK/image.png

Any chance to show list of stacks exploded at once?
1. Player 1 - 22 stacks
2. Player 2 - 16 stacks
3. Player 3 - 3 stacks
but not as total amout but as single explosion.

If it's too much effort just close the ticket : )

Regards,
Wojas

**Comment by bkader** [comment]
@wojas007, keep in mind that the fails module uses the LibFails libraryto catch fails, so whatever you see on the fails list is only what the library triggered to record. the module simply watches the CombatLog and it's the library that tells it what to record. I will have a more in depth look into it. Thanks a lot for your time and suggestions.

**Comment by wojas007** [comment]
Well I looked into the LibFails and there seems to be some not tested things. I really have no idea about lua code, but someone who wrote this at least added comments there:
https://i.ibb.co/jZgcnPQ/image.png

As the file is really long I don't think it's worth working on it. As I scrolled over it, there seems to be many unnecessary things there.
