### ISSUE TITLE
PlayerGUID bug breaks my combat log

### ISSUE THREAD

**Issue by foxtoopia12** [bkader/Skada-Revisited#14]
> Date: 2020-11-30 03:36:47
ID: 1
Error occured in: Global
Count: 134
Message: ..\AddOns\Skada\Skada.lua line 1136:
   Usage: GetPlayerInfoByGUID("playerGUID")
Debug:
   (tail call): ?
   [C]: GetPlayerInfoByGUID()
   Skada\Skada.lua:1136: FixPlayer()
   Skada\Skada.lua:1220: get_player()
   Skada\modules\Damage.lua:79:
      Skada\modules\Damage.lua:78
   Skada\modules\Damage.lua:235: func()
   Skada\Skada.lua:3038: ?()
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:147:
      ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:147
   [string "safecall Dispatcher[21]"]:4:
      [string "safecall Dispatcher[21]"]:4
   [C]: ?
   [string "safecall Dispatcher[21]"]:13: ?()
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:92: Fire()
   ...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119

Hm I got this bug and it broke my combat log, hence I did zero damage (lmao).
I also use combat log fix macro if it helps you for more information.

**Comment by bkader** [comment]
@foxtoopia12 did you update the addon? Because I am pretty sure that error was fixed! Please let me know.

**Comment by bkader** [comment]
I just updated the addon. Please give it a try and let me know if it's fixed so we can close this issue.
