### ISSUE TITLE
Can you somehow remove this extra space?

### ISSUE THREAD

**Issue by MaelKoT** [bkader/Skada-Revisited#16]
Can you somehow remove this extra space?
![image](https://user-images.githubusercontent.com/2527033/101744090-eccc6880-3adb-11eb-833f-b030da86d258.png)

And i have 1 question, skada-revisited still share data between themself? And with old-skada? If so, can we have option to turn off this function?

Why is this needed?
I recently ran into a situation like this:
The raid killed the boss, I got out of combat, but the data in skada still kept changing for ~ 20 seconds or more - I assumed that from a few bugged players there was information that the combat still ongoing.

**Comment by bkader** [comment]
Hello @MaelKoT and thanks for the feedback.

To answer your first question about the space there, there isn't a single line in the code that adds that space whatsoever, every element of a bar are literally sticked to each other, that's sadly just how it works for frames system in wow. Not only for addons but everything.

To answer your second question about Skada that keeps collecting data even if you're out of combat. Check the code below:
```
local function combat_tick()
    if not disabled and Skada.current and not InCombatLockdown() and not IsRaidInCombat() then
        Skada:EndSegment()
    end
end
```
This ticks every second and checks if the raid is out of combat, so if a single player is in a combat bug, Skada keep collecting.

**Comment by MaelKoT** [comment]
As far as I understand, now the addon will not record the segment until the player himself enters the battle?

Maybe you really need such an option in the settings, "finish the segment after the player leaves combat"? So that you can turn it off when you need to record all the battles of the raid.
It's just that this bug does not happen often (for me - in general, only in / after the battle with the ICC Saurfang)

**Comment by bkader** [comment]
> As far as I understand, now the addon will not record the segment until the player himself enters in combat?
Yes, that's how all damage meters addons (_should_) work.

> Maybe you really need such an option in the settings, "finish the segment after the player leaves combat"? So that you can turn it off when you need to record all the battles of the raid.
Let's assume we add that option as "Sensitive segment ending" that stops the addon from recording data the moment you go out of combat. This means even if 24 people are in combat and you're not, the addon stops, so technically, the data recorded when everyone finishs the combat will be tremendously wrong and bad because even when you die the combatlog considers you out of combat. Just think of the scenario where you start dpsing a boss, few seconds you die, the addon stops, then you spend few seconds waiting for someone to resurrect you, after you get up you will unfortunately start a new segment with whole new data. Do you think it's a good idea?

**Comment by bkader** [comment]
@MaelKoT if you understood why this is not a good idea and are convinced, let me know so I can close this issue.

**Comment by MaelKoT** [comment]
I just thought it would be convenient to have two options 
> 1. for normal raids
>  `if not disabled and Skada.current and not InCombatLockdown() and not IsRaidInCombat() then`
> 2. for troubled bugged boss fights
> `if not disabled and Skada.current and not InCombatLockdown() then`

to deal with the unfortunate bug that has plagued many game servers for many years, but if not, then no :(

**Comment by bkader** [comment]
I mean I don't mind modifying the code for you to test and see if it works for you, you'll just need to get the modified files and we'll see if the test for you. If you don't m8nd testing it, i don't mind modifying it.

**Comment by MaelKoT** [comment]
This change works very well. If the player normally ends combat at the end of fight, the recording segment will automatically end.

But, as you warned, this is not suitable for normal raids, because the segment stops also when the player dies ...
