### ISSUE TITLE
[Enhancement] Enabling a feature to edit the font size on bar separately

### ISSUE THREAD

**Issue by foxtoopia12** [bkader/Skada-Revisited#2]
This feature is from Details where we can edit the font size on the bar separately, meaning we can edit the font size of the name and the number separately since I sometimes wanna emphasize on the names rather than the numbers.
![image](https://user-images.githubusercontent.com/28296117/97589778-865e2000-1a30-11eb-9f3c-ac073a7e61eb.png)

**Comment by bkader** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/4732702/98045520-e980f580-1e28-11eb-8661-cba24b2b6851.png)
I already added it to the the **in-progress** version. I will close this issues once released.
