### ISSUE TITLE
SELF spec icon

### ISSUE THREAD

**Issue by wojas007** [bkader/Skada-Revisited#23]
Hello,
I often get wrong spec icon for MYSELF. Raid/party members are shown properly, but myself is often shown as red square or if I change spec then wrong icon is shown. Is that only my problem?

**Comment by bkader** [comment]
@wojas007 just noticed the issue of spec caching like 10min ago. It shows first spec if you swap to 2nd one, but I haven't encountered a red icon yet. I will look into it

**Comment by wojas007** [comment]
@bkader 

as for changing spec - yeah I noticed that too.

as for red square - it happens only for MYSELF when I login and join dungeon/raid. It takes very long for addon to "check" my spec (sometimes few encounters). After that is sometimes fixes itself.

**Comment by bkader** [comment]
@wojas007 I did a rollback to single time cache per segment instead of single load caching. Try it whenever you can please and let me know.

**Comment by wojas007** [comment]
@bkader 
Respec works fine. Also I didn't get red square as I did before. But I'd prefer to also check it on some raid, so let's keep this issue open till I raid. It seems fixed though.

**Comment by bkader** [comment]
Sure, you can keep it open for now, though it was working fine before just the caching system I added didn't work as expected.

**Comment by wojas007** [comment]
Hey @bkader 
It seems to be working very well now. I'm closing this topic
