### ISSUE TITLE
Window display bug

### ISSUE THREAD

**Issue by MaelKoT** [bkader/Skada-Revisited#24]
Window 1 always opens upward; while windows 2 and 3, as expected, expand to where there is more free space.
The same thing happens when you open these settings by right-clicking on the addon icon on the minimap.
The same thing happens with the Elvui skin too.
![image](https://user-images.githubusercontent.com/2527033/104067618-89397600-5214-11eb-8b1a-86955b34a139.png)

**Comment by bkader** [comment]
@MaelKoT thanks for reporting this, I will check it tomorrow morning hopefully.

**Comment by bkader** [comment]
<details>
<summary>Top Right</summary>
![Screenshot_12](https://user-images.githubusercontent.com/4732702/104089363-aa2eb500-526e-11eb-8ea0-d93bc9bacfcd.png)
</details>

<details>
<summary>Bottom Left</summary>
![Screenshot_13](https://user-images.githubusercontent.com/4732702/104089364-abf87880-526e-11eb-8da5-9c2fe3c88105.png)
</details>

<details>
<summary>Top Left</summary>
![Screenshot_14](https://user-images.githubusercontent.com/4732702/104089365-ad29a580-526e-11eb-95a0-
cafb504a0e14.png)
</details>

<details>
<summary>Bottom Right</summary>
![Screenshot_17](https://user-images.githubusercontent.com/4732702/104089366-adc23c00-526e-11eb-925b-d5b7da435619.png)
</details>

Here is what I see on my side, I don't know how the dropdown isn't smartly picking position on your side

**Comment by MaelKoT** [comment]
I think, this is because you have no saved segments
They are placed below the "current fight", which makes this list very long

**Comment by bkader** [comment]
Alright, i see what you mean.
The best solution for this is to either put mode menus under their categories like when you click on the window mode menu, or to simply eliminate the mode & segment menus from the minimap button to keep only lock/unlock and hide.

**Comment by bkader** [comment]
![Screenshot_18](https://user-images.githubusercontent.com/4732702/104094726-f68bec00-5292-11eb-8134-0f5a5affdd41.png)
![Screenshot_19](https://user-images.githubusercontent.com/4732702/104094728-f7bd1900-5292-11eb-8f7d-4e6eaf6deec5.png)
Something like this, is the only solution for that problem. Why is this better?
1. Windows have Modes/Segments buttons you can use to individually jump to mode/segment.
2. It is pointless to have Skada menu showing the exact same thing again and again (_aka Mode & Segment menus_)

**Comment by bkader** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/4732702/104124449-47621a00-5351-11eb-8e03-1884150317db.png)
I am closing this issue because this was added now as an option to choose short or default menus types. (_commit [bdaabdf](https://github.com/bkader/Skada-Revisited/commit/bdaabdf1459c195728014379e746bd4bbfec51f2)_).
