### ISSUE TITLE
Power gained: Mana not working properly

### ISSUE THREAD

**Issue by wojas007** [bkader/Skada-Revisited#26]
hey @bkader !
Today I noticed, that Power gained: Mana module is not working properly. Here's example of what I had after boss fight:
![image](https://user-images.githubusercontent.com/55255393/104514693-f3c22b80-55f1-11eb-8f2d-cd4b55cc2a00.png)
There's no replenishment or Innervate at all. Mana Tide has too much mana restored (it is impossible for 1 mana tide to restore so much mana).

I asked friend to show me what he saw on his addon:
![image](https://user-images.githubusercontent.com/55255393/104514847-397ef400-55f2-11eb-87a8-ce677acf151a.png)
Tese values seems more correct, HOWEVER I used mana potion and his addon didn't show that.

Another question:
Should buffs module show only my buffs? Or should I see buffs I get from other players too? Like replenishment?
![image](https://user-images.githubusercontent.com/55255393/104515053-89f65180-55f2-11eb-8285-76e11ab7f5cb.png)

Regards,
Wojas

**Comment by bkader** [comment]
Hey @wojas007 , thanks again for testing.
I will take a look into that mana restore module, I didn't work on it that much honestly.
As for buffs, it shows yours and buffs put on you (_aka auras_), for example Hysteria, Hero/Lust ... etc. I don't know for replenishment to be honest, I will have to check it.

**Comment by bkader** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/4732702/104600346-295e2780-5679-11eb-96aa-132757daacd9.png)
Hey @wojas007 , it should work fine now but needs to be stress-tested during a raid.

**Comment by wojas007** [comment]
Hey @bkader 
I wasn't able to play raid today, however I tested reworked module on my own. I think it still doesn't work as it should:
![image](https://user-images.githubusercontent.com/55255393/104639165-5e816e80-56a7-11eb-8df6-159e90d82fad.png)

At the moment module adds mana regenerated BY A SOURCE and shows total amount regenerated.
I think it should work a bit differenty - It should show how much a player gained mana during encounter FROM all sources (so should be added by target, not source).
On screenshot above you can see that Mana Tide restored 13,2k mana and it is all in Shaman's info, while Shaman gained only 7,2 and druid gained 6k from it.

And here in druid's details you can see innvervate and revitalize:
![image](https://user-images.githubusercontent.com/55255393/104639801-1e6ebb80-56a8-11eb-9946-241b0e9d87b0.png)
Both were cast on shaman, not druid.

Regards,
Wojas

**Comment by wojas007** [comment]
@bkader 
Unfortunately after testing new version by myself I noticed, that addon still adds mana "gained" by source, not target:
![image](https://user-images.githubusercontent.com/55255393/104641032-8a055880-56a9-11eb-95a9-8c2f4cd71349.png)

I think it should add mana gained by target from all sources

Regards,
Wojas

**Comment by bkader** [comment]
@wojas007 , I didn't get it, you mean if you innervate another player, the module records the mana gain to you instead of that player?

**Comment by bkader** [comment]
Thanks for reporting this @wojas007 , it was indeed a typo, SPELL_ENERGIZE should work fine now, still need to test SPELL_LEECH (_aka drain_).
Regards.

**Comment by wojas007** [comment]
Ok so solo testing shows that it should work fine now. Will try it during raid next time I play

**Comment by bkader** [comment]
Is it worth it to add the source? Like who innervate, from who the replenishment is... etc? Or is it going too much of unnecessary data?

**Comment by wojas007** [comment]
Well I thought of at first, but I think it's not needed. I can't think of a situation when you would want to check the source of your mana gained. Maybe only if you had 2 or more of same source of mana, but then it would be mostly RNG (replenishment, revitalize, etc). Innervate, Mana Tide, etc can be seen on different addons/modules, so I think it's unnecessary data.

**Comment by wojas007** [comment]
I tested module on raid and it works fine. Compared with other addons and numbers are the same. Closing this.
