### ISSUE TITLE
[Request] Deathlog changes?

### ISSUE THREAD

**Issue by MaelKoT** [bkader/Skada-Revisited#27]
Can we see Overkill, Absorbed and Resisted damage in deathlog?

Now everything looks like this
![image](https://user-images.githubusercontent.com/2527033/104611747-83211a80-5696-11eb-9581-b0a51fe6f7c5.png)

```
-Time: SpellName   -RecievingDamage (HP, HP%)
0.00: AA   -28.5K (25.6K, 33.2%)
-1.74: Ice breath   -45.7K (20.2К, 26,2%)
```

Can we change this like
```
-Time: SpellName   -RecievingDamage [O: , A: , R:] (HP, HP%)
0.00: AA   -28.5K [O:2.9K, A:5K] (25.6K, 33.2%)
-1.74: Ice breath   -45.7K [A:8.1K, R:35.8K] (20.2К, 26,2%)
```
for **O**verkill, **A**bsorbed and **R**esisted damage (which existed in combatlog)

SPELL_DAMAGE,0xF130008FF5000703,"Синдрагоса",0x10a48,0x0000000000346FB4,"Captainblac",0x80514,73064,"Ледяное дыхание",0x10,45694,0,16,**35837**,0,**8063**,nil,nil,nil

SWING_DAMAGE,0xF130008FF5000703,"Синдрагоса",0x10a48,0x0000000000346FB4,"Captainblac",0x80514,28514,**2866**,1,0,0,**5031**,nil,nil,nil

**Comment by bkader** [comment]
@MaelKoT wait few minutes :)

**Comment by bkader** [comment]
@MaelKoT [there you go](https://github.com/bkader/Skada-Revisited/commit/f29d005912bf1602f2a85748bf957d40a3d66731), keep this issue opened till the next time you try it and if it works, you can close it.

**Comment by bkader** [comment]
For the moment, those details are only shown on the tooltip, but I will change the info shown on the bars.

**Comment by MaelKoT** [comment]
Looks perfect, everything is as I imagined :D
