### ISSUE TITLE
Disabling Columns has no effect

### ISSUE THREAD

**Issue by pathetic-lynx** [bkader/Skada-Revisited#3]
It does not matter what I select under columns, Skada always shows everything.
Full disclosure: I am playing on a german server and the german localization does look a little bit incomplete tbh. Maybe thats part of the problem.

Looking into it

**Comment by bkader** [comment]
I have completely rewritten the code of the addon in order to get rid of what's unnecessary and to have a better idea who it was written. Next update will be a completely different Skada (_for 3.3.5_) - see [some screenshots](https://imgur.com/a/cvET7sC).

**Comment by pathetic-lynx** [comment]
Ok, I think I completetely missunderstood what that setting was supposed to do.
Very nice to see this addon has active development! :)
