### ISSUE TITLE
Enemies module real-time update

### ISSUE THREAD

**Issue by bkader** [bkader/Skada-Revisited#31]
Some people like to take a peek at `Enemy damage taken` or `Enemy damage done` modules to compare the damage they are doing on certain mobs to others. These modules were tweaked from the original and they no longer record any data by instead they read it from `Damage` and `Damage taken` modules respectively.

These modules will be updated to show real time numbers when clicking on a target.

**Comment by wojas007** [comment]
This is actually good in few cases. For example on Blood Prince Council you could check who did damage to nucleus **but with what abilities**.

**Comment by MaelKoT** [comment]
Or on Saurfang - find out who and how cleaved mobs.
Or on the Lich King - find out who is doing bullshit in the raid / hitting the spirits.

**Comment by bkader** [comment]
Both modules work fine, the only issue is that they only update the data once the fight ends. Someone was reporting this bug fir a while but I couldn't understand what they meant because they weren't bugged. until they showed me a stream of a live updated numbers during fights and this is how I understood them. 
The modules were changed but I need to test in a raid because I only tested on solo and they work fine.

**Comment by bkader** [comment]
https://user-images.githubusercontent.com/4732702/105485294-f33e2a80-5cac-11eb-810d-98e8515e7eee.mp4

This is how they should work now (_PS: Don't mind FPS drops on the video, I don't have a decent pc, simple laptop_).

**Comment by wojas007** [comment]
Oh I see so only real-time was the problem, right?

Question connected to this topic. Is it possible (or will it be possible) to check:
Enemy damage taken -> Player 1 -> **list of spells and their damage that Player 1 damaged this enemy with?**

**Comment by bkader** [comment]
The **Damage** (_done_) module needs to be slightly tweaked for that to work. I will stop at the list of spells and not go further because it will require more complexed tweaks to the module.

**Comment by wojas007** [comment]
So at the moment we have like this:
Enemy damage taken -> Target A -> list of players with damage value

After tweak it will be possible to clikck on player and see **list of spells with damage value?**

**Comment by bkader** [comment]
The actual is:
Enemy damage taken > Target > Players
After tweak:
Enemy damage taken > Target > Players > Spells
