### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by Noob1e** [bkader/Skada-Revisited#32]
![WoWScrnShot_012521_111639](https://user-images.githubusercontent.com/27544010/105679145-16601880-5eff-11eb-82f0-3e6144c51c57.jpg)
This screenshot has taken after a "skada reset" and relog. Isn't it "a bit" high?

**Comment by bkader** [comment]
Hi @Noob1e, thanks for the feedback.
Something is wrong on your side because, according to what you said, after reset a fresh setup there no way on earth it can reach that amount of memory.

**Comment by Noob1e** [comment]
So any idea how to fix that?

**Comment by bkader** [comment]
> So any idea how to fix that?

Well I have no idea how you installed the addon and whether you followed the fresh setup instructions or not but,
1. Can you tell me what Skada folders do you have inside AddOns folder?
2. Did you delete all old SavedVariables before launching the game?
We start with this then we'll see.

**Comment by Noob1e** [comment]
I deleted the "Skada.lua" in "SavedVariables" folder. Now it's fixed. Thanks for your help.
