### ISSUE TITLE
Red squares as icons again (more info)

### ISSUE THREAD

**Issue by wojas007** [bkader/Skada-Revisited#33]
Hey @bkader 
From time to time I still get red squares for icons, but today I have more info when they appear:
![image](https://user-images.githubusercontent.com/55255393/106147341-0868fc80-6178-11eb-84c3-a0f0212189e7.png)

So in the top window (threat) I have ROLE set as icons. Red squares appeared for:
1. Pets
2. Feral druid (he also changed spec from tanking feral to dpsing feral few times)
3. Priest (she changed spec from disci to shadow few times)

They didn't fix with reload/relog/combatlog fix and stayed as squares for whole raid.
I noticed pet ROLE problem just yesterday, but for disci/shadow/holy priests or balance/tank/feraldps/resto druids ROLE icon turns into squares very often (sometimes it fixes after few encounters and sometimes not).
This issue now happens only for ROLE (class or spec work fine).

Regards,
Wojas

**Comment by bkader** [comment]
@wojas007 thanks a lot for reporting this.
This only happens with the threat module right? If yes, then I will have to rewrite the module completely or at least get rid of those icons because the threat API is a bit screwed.. If other modules collect data first everything works fine, if it's that module that starts collecting data about players .. you know the result.
I will put more work into it.

**Comment by wojas007** [comment]
I actually didn't check if role icons were corrrect in other modules OR if threat module shows proper icons if they are other than roles.

**Comment by wojas007** [comment]
Quick info:
I checked the data from yesterday (when bug occured) and checked role icons for other modules. They seem fine. Maybe threat module could somehow call for role info from somewhere else to put icons properly?

What I cannot check outside raid: when role icons are bugged for threat module, then what happens if I change them for spec/class icon. Will test it next time I play

**Comment by bkader** [comment]
> 
> 
> I actually didn't check if role icons were corrrect in other modules OR if threat module shows proper icons if they are other than roles.

Pets didn't have "roles" assigned and it was my mistake. I added the missing lines to different files that assigns the role `DAMAGER` to them by default.

**Comment by wojas007** [comment]
> > I actually didn't check if role icons were corrrect in other modules OR if threat module shows proper icons if they are other than roles.
> 
> Pets didn't have "roles" assigned and it was my mistake. I added the missing lines to different files that assigns the role `DAMAGER` to them by default.

Yeah I figured that could be the problem for pets. Druids (all specs) and priest (all specs) are different story. This doesn't happen always. but sometimes it does

**Comment by wojas007** [comment]
I have a question @bkader 

How specs and roles are assigned?

**Comment by bkader** [comment]
Using the `LibGroupTalents-1.0` library.

**Comment by wojas007** [comment]
Ok then it's too complicated for me to help here : P

**Comment by bkader** [comment]
![Screenshot_16](https://user-images.githubusercontent.com/4732702/106155132-9fd24d80-6180-11eb-8db4-be3b60df738a.png)
This little tweak seems to work for now but if we want a more complicated threat module just like Omen's I will have to rewrite it.

**Comment by wojas007** [comment]
I don't really mind what these icons are. I only wanted to help get rid of red squares (unless this happens only for me) : p

**Comment by wojas007** [comment]
@bkader I did some testing and here's what I found (maybe that helps):
Threat module don't track spec changes. Remember this issue?
https://github.com/bkader/Skada-Revisited/issues/23
![image](https://user-images.githubusercontent.com/55255393/106160142-c9da3e80-6185-11eb-8425-65bbd253ad2c.png)

I logged my feral tank / feral dps druid and changed spec few times.
All the modules EXCEPT for the threat were able to assign proper icon (class, spec and role) after respec.
Only threat module was showing icons for spec/role that I logged in with.

**Comment by bkader** [comment]
@wojas007 thanks for testing and providing this amount of info!
Tell me please, did you update the addon or not? Because I added the backup roles/specs in [this commit](https://github.com/bkader/Skada-Revisited/commit/ea1dd880cc72805bdc2a23846addfb715b1c134b)

**Comment by wojas007** [comment]
After update threat module still doesn't check for respec. Spec/roles don't change after you change spec.

I didn't check for squares yet because I didn't have a chance to raid

**Comment by wojas007** [comment]
Hey @bkader !
Today I have a bit more info, because I had a chance to test newest version on raid. I need first to recall this:
![image](https://user-images.githubusercontent.com/55255393/106398090-42a0fb00-6411-11eb-9edf-d8087b8d191f.png)

What you wrote above is correct and sometimes happen. But this does **NOT bother** me, because it fixes itself for next fights.

However it does **NOT fix itself for threat module**. So if class/spec/role is "cached" wrongly for first encounter it will stay that way until relog/reload. So if red square appear in threat module for first fight you play, then it'll stay this way until relog. It is the same with respec - threat module won't update spec/role after changing spec.

But again - this is **ONLY for threat module**. Other modules work fine (even if loaded/cached wrongly, because they fix after time).

**Comment by bkader** [comment]
Hey @wojas007 and thanks again for the feedback.
Is there a chance you can edit the `modules\Threat.lua` file and change line **39** from `Skada:find_player` to `Skada:get_player` and comment out/delete line **41** and give it a test?

**Comment by wojas007** [comment]
I'll try it and let you know

**Comment by bkader** [comment]
> I'll try it and let you know

@wojas007 , try [this pastebin](https://pastebin.com/kPk96rpn) instead and let me know.

**Comment by wojas007** [comment]
Hey @bkader 
I was only able to test this solo and still there's no response to changing spec.
Will check for red squares when I play any raid, but I think that it will be the same as for changing spec.

**Comment by wojas007** [comment]
> > I'll try it and let you know
> 
> @wojas007 , try [this pastebin](https://pastebin.com/kPk96rpn) instead and let me know. If it works, it will be used instead.

@bkader 
I just tested this threat module. It seems that even if there are some red squares for first encounter, they seem to fix for next fights.

However, there is still something wrong with **spec** AND **role** caching. For some reason threat module sometimes reads change of spec and sometimes it doesn't:
![image](https://user-images.githubusercontent.com/55255393/106522299-cd502b80-64df-11eb-8859-1f5c71f12897.png)
- The druid pointed with green rectangle changed to balance from tank (threat module shows proper spec)
- The druid pointed with red rectangle changed to feral DPS from resto (threat module shows wrong spec)

I really don't know if it's worth working on... If not just close the topic.
Also I still need some testing for red squares (for some reason they mostly appear in ruby sanctum for me)

**Comment by bkader** [comment]
@wojas007 thanks a lot for your tests and sorry for all the troubles you are having.
I completely removed **specs** from the Threat module and I allowed only **class** or **role**, just like any other addons.
If the problem with red squares still occurs, I will just remove roles and keep only classes.

**Comment by wojas007** [comment]
> @wojas007 thanks a lot for your tests and sorry for all the troubles you are having.
> I completely removed **specs** from the Threat module and I allowed only **class** or **role**, just like any other addons.
> If the problem with red squares still occurs, I will just remove roles and keep only classes.

@bkader remove roles then, because roles bug sometimes with respec. Keep only classes.

**Comment by wojas007** [comment]
@bkader SOLO TESTS

after login
![image](https://user-images.githubusercontent.com/55255393/106525564-7862e400-64e4-11eb-9df4-486a6453701f.png)

after changing spec:
![image](https://user-images.githubusercontent.com/55255393/106525617-8a448700-64e4-11eb-9042-fed1478c59ab.png)
