### ISSUE TITLE
Errors (a nil value)

### ISSUE THREAD

**Issue by Artur91425** [bkader/Skada-Revisited#34]
Both of these errors appeared when I applied http://www.cavernoftime.com/?item=22218 on a draenei paladin. I play on the ruRU game client.
![WoWScrnShot_020821_203809](https://user-images.githubusercontent.com/24303693/107259710-63d79c00-6a4e-11eb-8788-fe0e558420fd.jpg)
![WoWScrnShot_020821_203916](https://user-images.githubusercontent.com/24303693/107259713-64703280-6a4e-11eb-93b9-ae03f0c01eca.jpg)

**Comment by Artur91425** [comment]
Another error appeared when hovering over the bar. I guess these errors are not related to the draenei paladin xD.
![image](https://user-images.githubusercontent.com/24303693/107260479-33dcc880-6a4f-11eb-939a-1eb6fa36bf4d.png)

**Comment by bkader** [comment]
This error should not appear at all. The fact that you got make me wonder how you proceeded to install the addon, whether you deleted old skada or not and of course if you deleted old savedvariables.
Try to re-install the addon fresh and clean by following the setup instructions on the README.md file on Github then try again.

**Comment by Artur91425** [comment]
Just downloaded the most recent version of the addon.
Deleted the WTF folder completely.
Loaded only 2 addons: Skada and Swatter
Upon entering the game world, I immediately get a new error...
![image](https://user-images.githubusercontent.com/24303693/107273605-55927b80-6a60-11eb-98a3-b8d8fb6237d5.png)

**Comment by Artur91425** [comment]
Before that, I had a version dated 12/23/2021, a couple of days ago I updated to the current one. There were errors when loading too (I thought it was due to a possible change of some variables). Therefore, I just opened the addon settings from the game and reset the profile. Everything worked without errors until today. Then I got an error with a non-existent variable set and performed the above steps.

**Comment by Artur91425** [comment]
I was able to reproduce the error of a non-existent variable set. I will record a video of how I do it.

**Comment by Artur91425** [comment]
Sorry for my very bad english. I hope you can understand me xD
P.S. WTF folder will be deleted before launch the game
https://youtu.be/8EBGwW_wDMs

**Comment by Artur91425** [comment]
> 
> 
> Another error appeared when hovering over the bar. I guess these errors are not related to the draenei paladin xD.
> ![image](https://user-images.githubusercontent.com/24303693/107260737-7d2d1800-6a4f-11eb-8b63-95c50376d21f.png)

This error also appears from a simple data reset...
1) open the menu where the modules are listed
2) select the segment "Current"
3) reset data
4) mouseover any of the bars

**Comment by bkader** [comment]
Do you have themes created?
