### ISSUE TITLE
Addon doesn't start collecting data until I go into combat

### ISSUE THREAD

**Issue by Pocokk** [bkader/Skada-Revisited#41]
Hey,

As the title says,  the addon isn't working until you join combat with other raid members/mobs, not like the original Skada, where it collects everything everytime.

**Comment by bkader** [comment]
Hello @Pocokk.
Have tried enabling `Aggressive Combat Detection`?

**Comment by Pocokk** [comment]
> 
> 
> Hello @Pocokk.
> Have tried enabling `Aggressive Combat Detection`?

I enabled it, let's see!

**Comment by Pocokk** [comment]
Working fine, thanks!
