### ISSUE TITLE
Can't make window's background transparent

### ISSUE THREAD

**Issue by gonrhcp** [bkader/Skada-Revisited#44]
I am trying to turn the background of the skada window transparent and I am not able to do so. This happens only when using the ElvUI Skin
![Sin título](https://user-images.githubusercontent.com/33702133/116940973-19417680-ac6f-11eb-9d94-605cfd0279bb.png)
I have tried turning opacity all the way down to 0 and setting texture to none, but still I'm not able
![Sin título2](https://user-images.githubusercontent.com/33702133/116940983-1f375780-ac6f-11eb-93ec-0f1a9f0da1f4.png)
Removing the ElvUI skin fixes the problem

**Comment by bkader** [comment]
The window background is 100% controlled ElvUI_AddOnSkins. You might want to choose transparent there not on Skada config.
And make sure to use the provided `ElvUI` and `ElvUI_AddOnsSkins` files.

**Comment by gonrhcp** [comment]
That's absolutely correct.
Changing the option in ElvUI_AddOnSkins to Transparent turned the window into a 40%ish transparecy window, but I believe this has to do with my global ElvUI settings. 
Having the option set to "None" definitely did the trick.

**Comment by bkader** [comment]
Glad this works! Closing the issue.
