### ISSUE TITLE
[Bug] Skada Doesn't Record Hunter Tranquilizing Shot as Dispel on Lich King Fight

### ISSUE THREAD

**Issue by foxtoopia12** [bkader/Skada-Revisited#6]
Description:
This Skada doesn't record hunter's tranquilizing shot when they use it to dispel Shambling Horror's Enrage on Lich King Fight

Step to Reproduce:
1. Open Skada
2. Navigate to Dispels

Expected Behavior: 
Hunter's Tranquilizing Shot should be recorded as Dispels.

Actual Behavior:
Hunter's Tranquilizing Shot isn't recorded as Dispels.

I also haven't raided Trial of the Crusader where Hunter can use Tranquilizing Shot to dispel enrage/magic, i.e Icehowl and Faction Champions. So I don't know if it works in TOC but in LK, their dispels aren't recorded as Dispels in Skada.

**Comment by foxtoopia12** [comment]
![image](https://user-images.githubusercontent.com/28296117/98411773-3ffc6700-20a9-11eb-906c-041b546f01d6.png)
Tranquiliing Shot is recorded as Priest's dispel.

**Comment by foxtoopia12** [comment]
Oh, on that image, it shows priest did cleanse whereas it is a Paladin's spell.

**Comment by bkader** [comment]
Yes I noticed. It didn't do that when I tested it in raid. I will have to check more.

**Comment by bkader** [comment]
@foxtoopia12 please try the recent update and let me know if it is still bugged so I can close the ticket.

**Comment by bkader** [comment]
I am closing this issue until I receive an update from you. I tested it and it's working just fine.
