### ISSUE TITLE
CC module

### ISSUE THREAD

**Issue by Zidras** [bkader/Skada-Revisited#8]
Hello. I had previously ported the cc done module and revised a grand majority of the cc spell ids. I'm at work but leaving this ticket open so I can upload the file when I can to give a contribution to this project

**Comment by bkader** [comment]
I had a very long list of CC spells before but I reduced it to the max possible. Thanks for the interest and you're welcome to contribute ofc

**Comment by Zidras** [comment]
Well, I'll leave it here for posterity I guess.

[cclist.zip](https://github.com/bkader/Skada-Revisited/files/5525931/cclist.zip)

**Comment by bkader** [comment]
I had all those spells and even more, but I lowered the list. If people want I can add them no worries.
